version: "3"

services:
  app:
    build: ../build
    ports:
      - "80:80"
      - "8080:8080"

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "calendar"
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "app_password"
    ports:
      - "5432:5432"